services:
  citadel:
    # build:
    #   context: ./Truncate
    #   dockerfile: Dockerfile.citadel

    image: ghcr.io/rlirli/truncate-citadel:latest
    container_name: truncate-citadel
    restart: unless-stopped
    networks:
      - internal # <--- Talks to DB here
      - web-routing # <--- Talks to Traefik here
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web-routing" # <--- THE FIX
      - "traefik.http.routers.truncate-citadel.rule=Host(`truncate.igbekele.de`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.truncate-citadel.entrypoints=websecure"
      - "traefik.http.routers.truncate-citadel.tls.certresolver=myresolver"
      - "traefik.http.services.truncate-citadel.loadbalancer.server.port=8080"
    environment:
      - DATABASE_URL=postgres://truncate:truncate@db:5432/truncate
      - SIGNING_SECRET=b0ea784ddf88ddd51cb4486e55a126604e4451c299046613646772563b035f68
      - RUST_LOG=debug
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: truncate-db
    restart: unless-stopped
    networks:
      - internal # <--- Only on internal network! Isolated from the web.
    environment:
      POSTGRES_USER: truncate
      POSTGRES_PASSWORD: truncate
      POSTGRES_DB: truncate
    volumes:
      - db-data:/var/lib/postgresql/data

  client:
    # build:
    #   context: ./Truncate
    #   dockerfile: Dockerfile.client

    image: ghcr.io/rlirli/truncate-client:latest
    container_name: truncate-client
    restart: unless-stopped
    networks:
      - web-routing # <--- Only needs Traefik access
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web-routing"
      - "traefik.http.routers.truncate-client.rule=Host(`truncate.igbekele.de`)"
      - "traefik.http.routers.truncate-client.entrypoints=websecure"
      - "traefik.http.routers.truncate-client.tls.certresolver=myresolver"
      - "traefik.http.services.truncate-client.loadbalancer.server.port=80"

networks:
  internal:
    internal: true
  web-routing:
    external: true

volumes:
  db-data:
